# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: microservice_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices_network

#  user-service:
#    build: ./user-service
#    container_name: user_service
#    depends_on:
#      - postgres
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
#      - GRPC_PORT=50051
#    ports:
#      - "50051:50051"
#    networks:
#      - microservices_network
#
#  book-service:
#    build: ./book-service
#    container_name: book_service
#    depends_on:
#      - postgres
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
#      - GRPC_PORT=50052
#    ports:
#      - "50052:50052"
#    networks:
#      - microservices_network

networks:
  microservices_network:
    driver: bridge

volumes:
  pgdata:
