// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: proto/book.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "bookproto";

export interface GetBookRequest {
  id: number;
}

export interface CreateBookRequest {
  title: string;
}

export interface BookResponse {
  data?: Book | undefined;
}

export interface Book {
  id: number;
  title: string;
}

export const BOOKPROTO_PACKAGE_NAME = "bookproto";

export interface BookServiceClient {
  getBook(request: GetBookRequest): Observable<BookResponse>;

  createBook(request: CreateBookRequest): Observable<BookResponse>;
}

export interface BookServiceController {
  getBook(request: GetBookRequest): Promise<BookResponse> | Observable<BookResponse> | BookResponse;

  createBook(request: CreateBookRequest): Promise<BookResponse> | Observable<BookResponse> | BookResponse;
}

export function BookServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getBook", "createBook"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BookService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BookService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BOOK_SERVICE_NAME = "BookService";
